name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        java: [8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install -U -DskipTests
        shell: bash -l {0}